# Render.com deployment configuration
services:
  # Backend API
  - type: web
    name: lumpy-pocket-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4001
    
  # Frontend static site
  - type: web
    name: lumpy-pocket-web
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    routes:
      - type: rewrite
        source: /api/*
        destination: https://lumpy-pocket-api.onrender.com/api/*